import * as THREE from 'three';
import type { AssetManager } from '@/lib/game/AssetManager';
import type { CombatSystem } from '@/lib/game/Combat';
import type { FloatingTextSystem } from '@/lib/game/FloatingText';
import type { GameState, NPC } from '@/lib/game/GameState';
import type { ParticleSystem } from '@/lib/game/ParticleSystem';
import type { ScreenShake } from '@/lib/game/ScreenShake';
import type { World } from '@/lib/game/World';
import type { BiomeAmbience } from '@/lib/game/BiomeAmbience';
import type { WeatherSystem } from '@/lib/game/WeatherSystem';
import type { DayNightCycle } from '@/lib/game/DayNightCycle';
import type { Direction8 } from '@/game/runtime/PlayerSimulationSystem';
import type { EnemyVisualRegistry } from '@/game/runtime/EnemyVisualRegistry';
import type { EnemyVisualProfile, NpcWanderState } from '@/game/runtime/RuntimeConfig';
import type { EnemyLoopContext, PortalHint, PortalWarpManagerLike } from '@/game/runtime/RuntimePhaseContexts';

export interface BuildRuntimePhaseContextsOptions {
  state: GameState;
  world: World;
  assetManager: AssetManager;
  combatSystem: CombatSystem;
  floatingText: FloatingTextSystem;
  screenShake: ScreenShake;
  particleSystem: ParticleSystem;
  biomeAmbience: BiomeAmbience;
  weatherSystem: WeatherSystem;
  dayNightCycle: DayNightCycle;
  scene: THREE.Scene;
  camera: THREE.OrthographicCamera;
  renderer: THREE.WebGLRenderer;
  activeNpcIndices: number[];
  npcData: NPC[];
  npcWander: Record<string, NpcWanderState>;
  isNpcPriorityCueTarget: (npc: NPC) => boolean;
  npcScaleById: Record<string, number>;
  npcFootOffset: number;
  getVisualYAt: (x: number, y: number) => number;
  getActorRenderOrder: (x: number, y: number, footOffset: number) => number;
  npcMeshes: THREE.Mesh[];
  npcShadows: THREE.Mesh[];
  npcOutlines: THREE.Mesh[];
  npcObjectiveHalos: THREE.Mesh[];
  npcObjectiveRings: THREE.Mesh[];
  checkInteraction: () => void;
  usePotion: () => void;
  keys: Record<string, boolean>;
  visitedTiles: Set<string>;
  getDirection8: (x: number, y: number) => Direction8;
  dir8to4: (direction: Direction8) => 'up' | 'down' | 'left' | 'right';
  performDodge: (moveX: number, moveY: number) => void;
  playFootstep: (isSprinting: boolean) => void;
  emitDust: (x: number, y: number) => void;
  emitHeal: (x: number, y: number, z: number) => void;
  triggerUIUpdateThrottled: (now: number) => void;
  triggerMinimapUpdate: (force?: boolean, now?: number) => void;
  blockStaminaCost: number;
  footstepInterval: number;
  attackFrameDuration: number;
  spinFrameDuration: number;
  spinDirections: Direction8[];
  idleFrameDuration: number;
  walkFrameDuration: number;
  chargeTimeMin: number;
  chargeTimeMax: number;
  textureCache: Map<string, THREE.Texture>;
  playerBaseScale: number;
  outlinePad: number;
  getPlayerTextureName: (direction: string, state: string, frame: number) => string;
  getPlayerVisualY: (x: number, y: number) => number;
  playerMesh: THREE.Mesh;
  playerMaterial: THREE.MeshBasicMaterial;
  playerOutline: THREE.Mesh;
  playerShadow: THREE.Mesh;
  bladeOverlayMesh: THREE.Mesh;
  heldItemMesh: THREE.Mesh;
  potionMaterial: THREE.MeshBasicMaterial;
  swooshMesh: THREE.Mesh;
  swooshMaterial: THREE.MeshBasicMaterial;
  spinSwooshMesh: THREE.Mesh;
  spinSwooshMaterial: THREE.MeshBasicMaterial;
  indicatorMesh: THREE.Mesh;
  indicatorMaterial: THREE.MeshBasicMaterial;
  objectiveIndicatorRingMesh: THREE.Mesh;
  objectiveIndicatorRingMaterial: THREE.MeshBasicMaterial;
  objectiveIndicatorOuterMesh: THREE.Mesh;
  objectiveIndicatorOuterMaterial: THREE.MeshBasicMaterial;
  essenceOrbMesh: THREE.Mesh;
  essenceOrbMaterial: THREE.MeshBasicMaterial;
  swooshDuration: number;
  getInteractionPromptLabel: (
    interactionId: string,
    promptState: GameState,
    promptWorld: World,
    x: number,
    y: number,
    npcName?: string,
  ) => string | null;
  isPortalDestinationUnlocked: (targetMap: string) => boolean;
  samplePortalNearPlayer: () => PortalHint | null;
  getMapDisplayName: (mapId: string) => string;
  criticalItemInteractionIds: Set<string>;
  isCollectedCriticalItem: (interactionId: string) => boolean;
  isChestOpened: (interactionId: string) => boolean;
  isConsumablePickupCollected: (interactionId: string, x: number, y: number) => boolean;
  setInteractionPrompt: (prompt: string | null) => void;
  criticalItemVisuals: { update: (currentTime: number, deltaTime: number) => void };
  transitionDebugManager: { rebuild: (playerPosition: { x: number; y: number }) => void };
  portalWarpManager: PortalWarpManagerLike;
  notify: (title: string, options?: { id?: string; description?: string; duration?: number }) => void;
  handleMapTransition: (targetMap: string, targetX: number, targetY: number) => void;
  enemyVisualProfiles: Record<string, EnemyVisualProfile>;
  enemyVisuals: EnemyVisualRegistry;
  enemyAudio: EnemyLoopContext['enemyAudio'];
  shadowGeometry: THREE.BufferGeometry;
  shadowMaterial: THREE.MeshBasicMaterial;
  createOutlineMesh: (geometry: THREE.BufferGeometry, texture: THREE.Texture | null) => THREE.Mesh;
  closeDialogueSession: () => void;
  setNpcScreenPos: (position: { x: number; y: number }) => void;
  npcScreenMinMs: number;
  npcScreenMinPx: number;
  autoSaveInterval: number;
  triggerSave: () => void;
}
