import type {
  EnemyLoopContext,
  GameplayPreludeContext,
  PlayerFrameContext,
  RuntimeLoopTailContext,
} from '@/game/runtime/RuntimePhaseContexts';
import type { BuildRuntimePhaseContextsOptions } from '@/game/runtime/RuntimePhaseBuilderOptions';

export function buildGameplayPreludeContext(options: BuildRuntimePhaseContextsOptions): GameplayPreludeContext {
  return {
    state: options.state,
    world: options.world,
    blockStaminaCost: options.blockStaminaCost ?? 0,
    triggerUIUpdateThrottled: options.triggerUIUpdateThrottled,
    activeNpcIndices: options.activeNpcIndices,
    npcData: options.npcData,
    npcWander: options.npcWander,
    isNpcPriorityCueTarget: options.isNpcPriorityCueTarget,
    npcScaleById: options.npcScaleById,
    npcFootOffset: options.npcFootOffset,
    getVisualYAt: options.getVisualYAt,
    getActorRenderOrder: options.getActorRenderOrder,
    npcMeshes: options.npcMeshes,
    npcShadows: options.npcShadows,
    npcOutlines: options.npcOutlines,
    npcObjectiveHalos: options.npcObjectiveHalos,
    npcObjectiveRings: options.npcObjectiveRings,
    checkInteraction: options.checkInteraction,
    usePotion: options.usePotion,
    keys: options.keys,
    visitedTiles: options.visitedTiles,
    getDirection8: options.getDirection8,
    dir8to4: options.dir8to4,
    performDodge: options.performDodge,
    playFootstep: options.playFootstep,
    emitDust: options.emitDust,
    emitHeal: options.emitHeal,
    triggerMinimapUpdate: options.triggerMinimapUpdate,
    footstepInterval: options.footstepInterval,
    attackFrameDuration: options.attackFrameDuration,
    spinFrameDuration: options.spinFrameDuration,
    spinDirections: options.spinDirections,
    idleFrameDuration: options.idleFrameDuration,
    walkFrameDuration: options.walkFrameDuration,
    chargeTimeMin: options.chargeTimeMin,
    chargeTimeMax: options.chargeTimeMax,
    lungeState: options.lungeState,
    combatSystem: options.combatSystem,
    onLungeHit: options.onLungeHit,
    onLungeEnd: options.onLungeEnd,
    dodgeIFrameDuration: options.dodgeIFrameDuration,
  };
}

export function buildPlayerFrameContext(options: BuildRuntimePhaseContextsOptions): PlayerFrameContext {
  return {
    state: options.state,
    world: options.world,
    assetManager: options.assetManager,
    textureCache: options.textureCache,
    playerBaseScale: options.playerBaseScale,
    outlinePad: options.outlinePad,
    getPlayerTextureName: options.getPlayerTextureName,
    dir8to4: options.dir8to4,
    getPlayerVisualY: options.getPlayerVisualY,
    getVisualYAt: options.getVisualYAt,
    meshes: {
      playerMesh: options.playerMesh,
      playerMaterial: options.playerMaterial,
      playerOutline: options.playerOutline,
      playerShadow: options.playerShadow,
      bladeOverlayMesh: options.bladeOverlayMesh,
      heldItemMesh: options.heldItemMesh,
      potionMaterial: options.potionMaterial,
      swooshMesh: options.swooshMesh,
      swooshMaterial: options.swooshMaterial,
      spinSwooshMesh: options.spinSwooshMesh,
      spinSwooshMaterial: options.spinSwooshMaterial,
      indicatorMesh: options.indicatorMesh,
      indicatorMaterial: options.indicatorMaterial,
      objectiveIndicatorRingMesh: options.objectiveIndicatorRingMesh,
      objectiveIndicatorRingMaterial: options.objectiveIndicatorRingMaterial,
      objectiveIndicatorOuterMesh: options.objectiveIndicatorOuterMesh,
      objectiveIndicatorOuterMaterial: options.objectiveIndicatorOuterMaterial,
      essenceOrbMesh: options.essenceOrbMesh,
      essenceOrbMaterial: options.essenceOrbMaterial,
    },
    swooshDuration: options.swooshDuration,
    screenShake: options.screenShake,
    getInteractionPromptLabel: options.getInteractionPromptLabel,
    isNpcPriorityCueTarget: options.isNpcPriorityCueTarget,
    isPortalDestinationUnlocked: options.isPortalDestinationUnlocked,
    samplePortalNearPlayer: options.samplePortalNearPlayer,
    samplePortalForWarpFoot: options.samplePortalForWarpFoot,
    getMapDisplayName: options.getMapDisplayName,
    criticalItemInteractionIds: options.criticalItemInteractionIds,
    isCollectedCriticalItem: options.isCollectedCriticalItem,
    isChestOpened: options.isChestOpened,
    isConsumablePickupCollected: options.isConsumablePickupCollected,
    setInteractionPrompt: options.setInteractionPrompt,
    criticalItemVisuals: options.criticalItemVisuals,
    transitionDebugManager: options.transitionDebugManager,
    portalWarpManager: options.portalWarpManager,
    notify: options.notify,
    handleMapTransition: options.handleMapTransition,
    handlePortalTransition: options.handlePortalTransition,
    lungeState: options.lungeState,
  };
}

export function buildEnemyLoopContext(options: BuildRuntimePhaseContextsOptions): EnemyLoopContext {
  return {
    scene: options.scene,
    assetManager: options.assetManager,
    combatSystem: options.combatSystem,
    state: options.state,
    world: options.world,
    floatingText: options.floatingText,
    screenShake: options.screenShake,
    outlinePad: options.outlinePad,
    enemyVisualProfiles: options.enemyVisualProfiles,
    registry: options.enemyVisuals,
    enemyAudio: options.enemyAudio,
    playPlayerHit: options.playPlayerHit,
    shadowGeometry: options.shadowGeometry,
    shadowMaterial: options.shadowMaterial,
    createOutlineMesh: options.createOutlineMesh,
    getVisualYAt: options.getVisualYAt,
    getActorRenderOrder: options.getActorRenderOrder,
  };
}

export function buildRuntimeLoopTailContext(options: BuildRuntimePhaseContextsOptions): RuntimeLoopTailContext {
  return {
    scene: options.scene,
    world: options.world,
    camera: options.camera,
    renderer: options.renderer,
    getVisualYAt: options.getVisualYAt,
    closeDialogueSession: options.closeDialogueSession,
    setNpcScreenPos: options.setNpcScreenPos,
    npcScreenMinMs: options.npcScreenMinMs,
    npcScreenMinPx: options.npcScreenMinPx,
    biomeAmbience: options.biomeAmbience,
    weatherSystem: options.weatherSystem,
    dayNightCycle: options.dayNightCycle,
    floatingText: options.floatingText,
    particleSystem: options.particleSystem,
    autoSaveInterval: options.autoSaveInterval,
    triggerSave: options.triggerSave,
  };
}
