import type { MapDefinition } from '@/data/mapGenerator';

export const interiorCottageForestDef: MapDefinition = {
  name: 'Cottage Interior',
  width: 12,
  height: 10,
  spawnPoint: { x: 6, y: 8 },
  seed: 9014,
  baseTerrain: 'forest',
  borderTile: 'stone',
  autoRoads: false,
  features: [
    { x: 2, y: 2, width: 8, height: 6, type: 'clearing', fill: 'wood_floor' },
    { x: 0, y: 0, width: 12, height: 2, type: 'wall', fill: 'stone' },
    { x: 0, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 10, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 2, y: 8, width: 3, height: 2, type: 'wall', fill: 'stone' },
    { x: 7, y: 8, width: 3, height: 2, type: 'wall', fill: 'stone' },
  ],
  portals: [{ x: 6, y: 9, targetMap: 'forest', targetX: 173, targetY: 96 }],
  chests: [{ x: 9, y: 6, interactionId: 'forest_cottage_chest' }],
  interactables: [],
  props: [
    { x: 4, y: 4, type: 'table', walkable: false },
    { x: 8, y: 4, type: 'bench', walkable: false },
    { x: 6, y: 6, type: 'rug', walkable: true },
    { x: 9, y: 3, type: 'pot', walkable: true },
    { x: 3, y: 3, type: 'bed', walkable: false },
    { x: 3, y: 6, type: 'wardrobe', walkable: false },
    { x: 8, y: 3, type: 'bed', walkable: false },
    { x: 3, y: 5, type: 'fireplace', walkable: false },
  ],
};

export const interiorRangerCabinDef: MapDefinition = {
  name: 'Ranger Cabin',
  width: 14,
  height: 10,
  spawnPoint: { x: 7, y: 2 },
  seed: 9005,
  baseTerrain: 'forest',
  borderTile: 'stone',
  autoRoads: false,
  features: [
    { x: 2, y: 2, width: 10, height: 6, type: 'clearing', fill: 'wood_floor' },
    { x: 0, y: 0, width: 14, height: 2, type: 'wall', fill: 'stone' },
    { x: 0, y: 2, width: 2, height: 6, type: 'wall', fill: 'stone' },
    { x: 12, y: 2, width: 2, height: 6, type: 'wall', fill: 'stone' },
    { x: 0, y: 8, width: 5, height: 2, type: 'wall', fill: 'stone' },
    { x: 9, y: 8, width: 5, height: 2, type: 'wall', fill: 'stone' },
  ],
  portals: [{ x: 7, y: 9, targetMap: 'forest', targetX: 141, targetY: 172 }],
  chests: [{ x: 10, y: 5, interactionId: 'forest_ranger_chest' }],
  interactables: [{ x: 7, y: 4, type: 'sign', walkable: false, interactionId: 'ranger_sign' }],
  props: [
    { x: 7, y: 3, type: 'table', walkable: false },
    { x: 4, y: 5, type: 'crate', walkable: false },
    { x: 5, y: 5, type: 'crate', walkable: false },
    { x: 10, y: 4, type: 'bookshelf', walkable: false },
    { x: 3, y: 6, type: 'bench', walkable: false },
    { x: 11, y: 6, type: 'bench', walkable: false },
    { x: 3, y: 3, type: 'bed', walkable: false },
    { x: 11, y: 3, type: 'bed', walkable: false },
    { x: 6, y: 6, type: 'fireplace', walkable: false },
    { x: 4, y: 3, type: 'wardrobe', walkable: false },
  ],
};

export const interiorWoodcutterCottageDef: MapDefinition = {
  name: "Woodcutter's Cottage",
  width: 12,
  height: 10,
  spawnPoint: { x: 6, y: 8 },
  seed: 9011,
  baseTerrain: 'forest',
  borderTile: 'stone',
  autoRoads: false,
  features: [
    { x: 2, y: 2, width: 8, height: 6, type: 'clearing', fill: 'wood_floor' },
    { x: 0, y: 0, width: 12, height: 2, type: 'wall', fill: 'stone' },
    { x: 0, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 10, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 2, y: 8, width: 3, height: 2, type: 'wall', fill: 'stone' },
    { x: 7, y: 8, width: 3, height: 2, type: 'wall', fill: 'stone' },
  ],
  portals: [{ x: 6, y: 9, targetMap: 'forest', targetX: 93, targetY: 186 }],
  chests: [],
  interactables: [],
  props: [
    { x: 3, y: 3, type: 'bed', walkable: false },
    { x: 3, y: 5, type: 'fireplace', walkable: false },
    { x: 4, y: 4, type: 'table', walkable: false },
    { x: 8, y: 4, type: 'weapon_rack', walkable: false },
    { x: 8, y: 5, type: 'crate', walkable: false },
    { x: 9, y: 4, type: 'barrel', walkable: false },
    { x: 7, y: 6, type: 'bench', walkable: false },
    { x: 3, y: 6, type: 'wardrobe', walkable: false },
  ],
};

export const interiorHunterCottageDef: MapDefinition = {
  name: 'Disparaged Cottage',
  width: 12,
  height: 10,
  spawnPoint: { x: 6, y: 8 },
  seed: 9010,
  baseTerrain: 'dungeon',
  borderTile: 'stone',
  autoRoads: false,
  features: [
    { x: 2, y: 2, width: 8, height: 6, type: 'clearing', fill: 'wood_floor' },
    { x: 0, y: 0, width: 12, height: 2, type: 'wall', fill: 'stone' },
    { x: 0, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 10, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 2, y: 8, width: 3, height: 2, type: 'wall', fill: 'stone' },
    { x: 7, y: 8, width: 3, height: 2, type: 'wall', fill: 'stone' },
  ],
  portals: [{ x: 6, y: 9, targetMap: 'forest', targetX: 137, targetY: 188 }],
  chests: [{ x: 8, y: 5, interactionId: 'forest_hunter_chest' }],
  interactables: [{ x: 6, y: 4, type: 'table', walkable: false, interactionId: 'hunter_clue' }],
  props: [
    { x: 3, y: 3, type: 'bed', walkable: false },
    { x: 8, y: 3, type: 'crate', walkable: false },
    { x: 9, y: 3, type: 'barrel', walkable: false },
    { x: 8, y: 4, type: 'crate', walkable: false },
    { x: 3, y: 5, type: 'fireplace', walkable: false },
    { x: 4, y: 4, type: 'bones', walkable: true },
    { x: 5, y: 6, type: 'bloodstain', walkable: true },
    { x: 7, y: 6, type: 'bloodstain', walkable: true },
    { x: 9, y: 5, type: 'barrel', walkable: false },
    { x: 6, y: 6, type: 'rug', walkable: true },
  ],
};
