import type { MapDefinition } from '@/data/mapGenerator';

export const interiorHollowArenaDef: MapDefinition = {
  name: 'The Hollow',
  subtitle: 'Lair of the Apparition',
  width: 36,
  height: 36,
  spawnPoint: { x: 18, y: 32 },
  seed: 9100,
  baseTerrain: 'forest',
  borderTile: 'dead_tree',
  autoRoads: false,
  coastalSouthBorder: false,
  features: [
    { x: 0, y: 0, width: 36, height: 3, type: 'wall', fill: 'dead_tree' },
    { x: 0, y: 33, width: 36, height: 3, type: 'wall', fill: 'dead_tree' },
    { x: 0, y: 3, width: 3, height: 30, type: 'wall', fill: 'dead_tree' },
    { x: 33, y: 3, width: 3, height: 30, type: 'wall', fill: 'dead_tree' },
    { x: 3, y: 3, width: 30, height: 30, type: 'clearing', fill: 'dark_grass' },
    { x: 10, y: 10, width: 16, height: 16, type: 'clearing', fill: 'mossy_stone' },
    { x: 13, y: 13, width: 10, height: 10, type: 'clearing', fill: 'ruins_floor' },
  ],
  portals: [],
  chests: [],
  interactables: [],
  props: [
    { x: 10, y: 10, type: 'statue', walkable: false },
    { x: 25, y: 10, type: 'statue', walkable: false },
    { x: 10, y: 25, type: 'statue', walkable: false },
    { x: 25, y: 25, type: 'statue', walkable: false },
    { x: 14, y: 8, type: 'bones', walkable: true },
    { x: 22, y: 7, type: 'bones', walkable: true },
    { x: 8, y: 16, type: 'bones', walkable: true },
    { x: 27, y: 20, type: 'bones', walkable: true },
    { x: 6, y: 15, type: 'bones', walkable: true },
    { x: 28, y: 12, type: 'bones', walkable: true },
    { x: 16, y: 28, type: 'bones', walkable: true },
    { x: 20, y: 6, type: 'bones', walkable: true },
    // Spent ritual — the Apparition was created here
    { x: 18, y: 14, type: 'heresy_altar_cracked', walkable: true },
    { x: 18, y: 8,  type: 'tombstone_broken',     walkable: true },
    // Corruption creeping from the north wall
    { x: 5,  y: 5,  type: 'dead_tree',   walkable: false },
    { x: 30, y: 5,  type: 'dead_tree',   walkable: false },
    // Ritual bone arrangements — deliberate, not random scatter
    { x: 15, y: 11, type: 'bones', walkable: true },
    { x: 21, y: 11, type: 'bones', walkable: true },
    { x: 12, y: 18, type: 'bones', walkable: true },
    { x: 24, y: 18, type: 'bones', walkable: true },
    // Evidence of previous challengers
    { x: 8,  y: 8,  type: 'bloodstain', walkable: true },
    { x: 26, y: 9,  type: 'bloodstain', walkable: true },
    { x: 9,  y: 24, type: 'bloodstain', walkable: true },
    { x: 27, y: 26, type: 'bloodstain', walkable: true },
  ],
};
