import type { MapDefinition } from '@/data/mapGenerator';

export const interiorHollowArenaDef: MapDefinition = {
  name: 'The Hollow',
  subtitle: 'Lair of the Apparition',
  width: 36,
  height: 36,
  spawnPoint: { x: 18, y: 32 },
  seed: 9100,
  baseTerrain: 'forest',
  borderTile: 'dead_tree',
  autoRoads: false,
  coastalSouthBorder: false,
  features: [
    { x: 0, y: 0, width: 36, height: 3, type: 'wall', fill: 'dead_tree' },
    { x: 0, y: 33, width: 36, height: 3, type: 'wall', fill: 'dead_tree' },
    { x: 0, y: 3, width: 3, height: 30, type: 'wall', fill: 'dead_tree' },
    { x: 33, y: 3, width: 3, height: 30, type: 'wall', fill: 'dead_tree' },
    { x: 3, y: 3, width: 30, height: 30, type: 'clearing', fill: 'dark_grass' },
    { x: 10, y: 10, width: 16, height: 16, type: 'clearing', fill: 'mossy_stone' },
    { x: 13, y: 13, width: 10, height: 10, type: 'clearing', fill: 'ruins_floor' },
  ],
  portals: [],
  chests: [
    { x: 5, y: 5, interactionId: 'hollow_arena_chest_nw' },
    { x: 30, y: 5, interactionId: 'hollow_arena_chest_ne' },
    { x: 5, y: 30, interactionId: 'hollow_arena_chest_sw' },
  ],
  interactables: [],
  props: [
    { x: 10, y: 10, type: 'statue', walkable: false },
    { x: 25, y: 10, type: 'statue', walkable: false },
    { x: 10, y: 25, type: 'statue', walkable: false },
    { x: 25, y: 25, type: 'statue', walkable: false },
    { x: 14, y: 8, type: 'bones', walkable: true },
    { x: 22, y: 7, type: 'bones', walkable: true },
    { x: 8, y: 16, type: 'bones', walkable: true },
    { x: 27, y: 20, type: 'bones', walkable: true },
    { x: 6, y: 15, type: 'bones', walkable: true },
    { x: 28, y: 12, type: 'bones', walkable: true },
    { x: 16, y: 28, type: 'bones', walkable: true },
    { x: 20, y: 6, type: 'bones', walkable: true },
  ],
};
