import type { MapDefinition } from '@/data/mapGenerator';

export const interiorInnDef: MapDefinition = {
  name: 'Greenleaf Inn',
  width: 20,
  height: 14,
  spawnPoint: { x: 10, y: 12 },
  seed: 9001,
  baseTerrain: 'grassland',
  borderTile: 'stone',
  autoRoads: false,
  features: [
    { x: 2, y: 2, width: 16, height: 10, type: 'clearing', fill: 'wood_floor' },
    { x: 0, y: 0, width: 20, height: 2, type: 'wall', fill: 'stone' },
    { x: 0, y: 2, width: 2, height: 10, type: 'wall', fill: 'stone' },
    { x: 18, y: 2, width: 2, height: 10, type: 'wall', fill: 'stone' },
    { x: 0, y: 12, width: 8, height: 2, type: 'wall', fill: 'stone' },
    { x: 12, y: 12, width: 8, height: 2, type: 'wall', fill: 'stone' },
  ],
  portals: [{ x: 10, y: 13, targetMap: 'village', targetX: 179, targetY: 94 }],
  chests: [],
  interactables: [],
  props: [
    { x: 10, y: 2, type: 'fireplace', walkable: false },
    { x: 6, y: 6, type: 'table', walkable: false },
    { x: 10, y: 6, type: 'table', walkable: false },
    { x: 14, y: 6, type: 'table', walkable: false },
    { x: 5, y: 8, type: 'bench', walkable: false },
    { x: 15, y: 8, type: 'bench', walkable: false },
    { x: 3, y: 5, type: 'barrel', walkable: false },
    { x: 17, y: 5, type: 'barrel', walkable: false },
    { x: 10, y: 9, type: 'rug', walkable: true },
    { x: 8, y: 3, type: 'counter', walkable: false },
    { x: 12, y: 3, type: 'counter', walkable: false },
    { x: 3, y: 3, type: 'bed', walkable: false },
    { x: 17, y: 3, type: 'bed', walkable: false },
    { x: 2, y: 9, type: 'wardrobe', walkable: false },
  ],
};

export const interiorBlacksmithDef: MapDefinition = {
  name: 'Village Smithy',
  width: 16,
  height: 12,
  spawnPoint: { x: 8, y: 10 },
  seed: 9002,
  baseTerrain: 'grassland',
  borderTile: 'stone',
  autoRoads: false,
  features: [
    { x: 2, y: 2, width: 12, height: 8, type: 'clearing', fill: 'stone' },
    { x: 0, y: 0, width: 16, height: 2, type: 'wall', fill: 'stone' },
    { x: 0, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 14, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 0, y: 10, width: 6, height: 2, type: 'wall', fill: 'stone' },
    { x: 10, y: 10, width: 6, height: 2, type: 'wall', fill: 'stone' },
  ],
  portals: [{ x: 8, y: 11, targetMap: 'village', targetX: 159, targetY: 64 }],
  chests: [],
  interactables: [],
  props: [
    { x: 8, y: 2, type: 'fireplace', walkable: false },
    { x: 4, y: 5, type: 'crate', walkable: false },
    { x: 5, y: 5, type: 'crate', walkable: false },
    { x: 11, y: 5, type: 'barrel', walkable: false },
    { x: 12, y: 5, type: 'barrel', walkable: false },
    { x: 3, y: 7, type: 'counter', walkable: false },
    { x: 7, y: 7, type: 'counter', walkable: false },
    { x: 11, y: 7, type: 'counter', walkable: false },
    { x: 4, y: 3, type: 'weapon_rack', walkable: false },
    { x: 3, y: 3, type: 'barrel', walkable: false },
  ],
};

export const interiorMerchantDef: MapDefinition = {
  name: 'Potion Shop',
  width: 14,
  height: 12,
  spawnPoint: { x: 7, y: 10 },
  seed: 9003,
  baseTerrain: 'grassland',
  borderTile: 'stone',
  autoRoads: false,
  features: [
    { x: 2, y: 2, width: 10, height: 8, type: 'clearing', fill: 'wood_floor' },
    { x: 0, y: 0, width: 14, height: 2, type: 'wall', fill: 'stone' },
    { x: 0, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 12, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 0, y: 10, width: 5, height: 2, type: 'wall', fill: 'stone' },
    { x: 9, y: 10, width: 5, height: 2, type: 'wall', fill: 'stone' },
  ],
  portals: [{ x: 7, y: 11, targetMap: 'village', targetX: 179, targetY: 62 }],
  chests: [],
  interactables: [],
  props: [
    { x: 3, y: 3, type: 'bookshelf', walkable: false },
    { x: 10, y: 3, type: 'bookshelf', walkable: false },
    { x: 5, y: 6, type: 'counter', walkable: false },
    { x: 9, y: 6, type: 'counter', walkable: false },
    { x: 4, y: 8, type: 'pot', walkable: true },
    { x: 10, y: 8, type: 'pot', walkable: true },
    { x: 6, y: 5, type: 'crate', walkable: false },
    { x: 8, y: 5, type: 'crate', walkable: false },
    { x: 7, y: 3, type: 'alchemy_table', walkable: false },
    { x: 3, y: 5, type: 'cauldron', walkable: false },
    { x: 11, y: 5, type: 'cauldron', walkable: false },
  ],
};

export const interiorCottageADef: MapDefinition = {
  name: 'Cottage Interior',
  width: 12,
  height: 10,
  spawnPoint: { x: 6, y: 8 },
  seed: 9004,
  baseTerrain: 'grassland',
  borderTile: 'stone',
  autoRoads: false,
  features: [
    { x: 2, y: 2, width: 8, height: 6, type: 'clearing', fill: 'wood_floor' },
    { x: 0, y: 0, width: 12, height: 2, type: 'wall', fill: 'stone' },
    { x: 0, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 10, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 2, y: 8, width: 3, height: 2, type: 'wall', fill: 'stone' },
    { x: 7, y: 8, width: 3, height: 2, type: 'wall', fill: 'stone' },
  ],
  portals: [{ x: 6, y: 9, targetMap: 'village', targetX: 91, targetY: 119 }],
  chests: [{ x: 9, y: 6, interactionId: 'cottage_interior_chest_a' }],
  interactables: [],
  props: [
    { x: 4, y: 4, type: 'table', walkable: false },
    { x: 8, y: 4, type: 'bench', walkable: false },
    { x: 6, y: 6, type: 'rug', walkable: true },
    { x: 9, y: 3, type: 'pot', walkable: true },
    { x: 3, y: 3, type: 'bed', walkable: false },
    { x: 3, y: 6, type: 'wardrobe', walkable: false },
    { x: 8, y: 3, type: 'bed', walkable: false },
    { x: 3, y: 5, type: 'fireplace', walkable: false },
  ],
};
