import type { MapDefinition } from '@/data/mapGenerator';

export const interiorWitchHutDef: MapDefinition = {
  name: 'Witch Hut',
  width: 12,
  height: 10,
  spawnPoint: { x: 6, y: 2 },
  seed: 9006,
  baseTerrain: 'swamp',
  borderTile: 'stone',
  autoRoads: false,
  features: [
    { x: 2, y: 2, width: 8, height: 6, type: 'clearing', fill: 'wood_floor' },
    { x: 0, y: 0, width: 12, height: 2, type: 'wall', fill: 'stone' },
    { x: 0, y: 2, width: 2, height: 6, type: 'wall', fill: 'stone' },
    { x: 10, y: 2, width: 2, height: 6, type: 'wall', fill: 'stone' },
    { x: 0, y: 8, width: 4, height: 2, type: 'wall', fill: 'stone' },
    { x: 8, y: 8, width: 4, height: 2, type: 'wall', fill: 'stone' },
  ],
  portals: [{ x: 6, y: 9, targetMap: 'deep_woods', targetX: 65, targetY: 68 }],
  chests: [],
  interactables: [{ x: 6, y: 4, type: 'sign', walkable: false, interactionId: 'witch_hut_lore' }],
  props: [
    { x: 3, y: 3, type: 'bookshelf', walkable: false },
    { x: 9, y: 3, type: 'bookshelf', walkable: false },
    { x: 6, y: 5, type: 'fireplace', walkable: false },
    { x: 4, y: 6, type: 'pot', walkable: true },
    { x: 8, y: 6, type: 'pot', walkable: true },
    { x: 5, y: 4, type: 'counter', walkable: false },
    { x: 3, y: 5, type: 'cauldron', walkable: false },
    { x: 9, y: 5, type: 'cauldron', walkable: false },
    { x: 6, y: 3, type: 'alchemy_table', walkable: false },
    { x: 4, y: 4, type: 'bones', walkable: true },
    { x: 8, y: 4, type: 'bones_pile', walkable: true },
  ],
};

export const interiorWitchCottageDef: MapDefinition = {
  name: "Witch's Cottage",
  width: 12,
  height: 10,
  spawnPoint: { x: 6, y: 8 },
  seed: 9015,
  baseTerrain: 'forest',
  borderTile: 'stone',
  autoRoads: false,
  features: [
    { x: 2, y: 2, width: 8, height: 6, type: 'clearing', fill: 'wood_floor' },
    { x: 0, y: 0, width: 12, height: 2, type: 'wall', fill: 'stone' },
    { x: 0, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 10, y: 2, width: 2, height: 8, type: 'wall', fill: 'stone' },
    { x: 2, y: 8, width: 3, height: 2, type: 'wall', fill: 'stone' },
    { x: 7, y: 8, width: 3, height: 2, type: 'wall', fill: 'stone' },
  ],
  portals: [{ x: 6, y: 9, targetMap: 'forest', targetX: 233, targetY: 136 }],
  chests: [{ x: 9, y: 6, interactionId: 'forest_witch_chest' }],
  interactables: [{ x: 6, y: 4, type: 'sign', walkable: false, interactionId: 'witch_cottage' }],
  props: [
    { x: 3, y: 3, type: 'bookshelf', walkable: false },
    { x: 9, y: 3, type: 'bookshelf', walkable: false },
    { x: 6, y: 5, type: 'cauldron', walkable: false },
    { x: 4, y: 6, type: 'pot', walkable: true },
    { x: 8, y: 6, type: 'pot', walkable: true },
    { x: 5, y: 4, type: 'counter', walkable: false },
    { x: 7, y: 4, type: 'counter', walkable: false },
    { x: 3, y: 5, type: 'alchemy_table', walkable: false },
    { x: 9, y: 5, type: 'fireplace', walkable: false },
  ],
};
