import type { MapDefinition } from '@/data/mapGenerator';

export const deepWoodsDef: MapDefinition = {
  name: 'The Deep Woods',
  subtitle: 'Light does not reach this far in',
  width: 240,
  height: 200,
  spawnPoint: { x: 120, y: 190 },
  seed: 256,
  baseTerrain: 'swamp',
  borderTile: 'tree',
  features: [
    { x: 50, y: 52, width: 24, height: 20, type: 'clearing', fill: 'swamp' },
    { x: 44, y: 54, width: 36, height: 24, type: 'clearing', fill: 'dirt' },
    { x: 60, y: 60, width: 10, height: 8, type: 'inn_building', interactionId: 'witch_hut', interiorMap: 'interior_witch_hut', interiorSpawnX: 6, interiorSpawnY: 2 },
    { x: 160, y: 40, width: 24, height: 20, type: 'ruins' },
    { x: 100, y: 100, width: 40, height: 30, type: 'clearing', fill: 'grass' },
    { x: 110, y: 110, width: 20, height: 12, type: 'garden' },
    { x: 92, y: 88, width: 36, height: 18, type: 'clearing', fill: 'stone' },
    { x: 40, y: 120, width: 32, height: 24, type: 'lake' },
    { x: 52, y: 130, width: 8, height: 4, type: 'bridge' },
    { x: 180, y: 140, width: 24, height: 18, type: 'lake' },
    { x: 180, y: 80, width: 30, height: 24, type: 'clearing', fill: 'dirt' },
    { x: 186, y: 86, width: 16, height: 12, type: 'camp', interactionId: 'shadow_den' },
    { x: 110, y: 20, width: 20, height: 16, type: 'ruins', interactionId: 'temple_entrance' },
    { x: 172, y: 4, width: 22, height: 26, type: 'waterfall' },
    { x: 20, y: 20, width: 30, height: 25, type: 'clearing', fill: 'dirt' },
    { x: 200, y: 160, width: 20, height: 16, type: 'clearing', fill: 'swamp' },
    { x: 108, y: 154, width: 24, height: 28, type: 'clearing', fill: 'dirt' },
    { x: 160, y: 160, width: 15, height: 12, type: 'garden' },
    { x: 90, y: 40, width: 20, height: 20, type: 'boss_arena', interactionId: 'deep_woods_guardian' },
    { x: 85, y: 35, width: 30, height: 30, type: 'clearing', fill: 'stone' },
    { x: 30, y: 160, width: 12, height: 10, type: 'abandoned_camp', interactionId: 'lost_scholars' },
    { x: 210, y: 120, width: 14, height: 10, type: 'abandoned_camp', interactionId: 'fallen_knights' },
    { x: 150, y: 100, width: 18, height: 14, type: 'cemetery' },
    { x: 116, y: 160, width: 8, height: 36, type: 'path', fill: 'dirt' },
    { x: 60, y: 100, width: 60, height: 6, type: 'path', fill: 'dirt' },
    { x: 120, y: 100, width: 60, height: 6, type: 'path', fill: 'dirt' },
    { x: 116, y: 20, width: 8, height: 80, type: 'path', fill: 'dirt' },
    { x: 96, y: 44, width: 8, height: 56, type: 'path', fill: 'stone' },
    { x: 60, y: 60, width: 56, height: 6, type: 'path', fill: 'dirt' },
    { x: 52, y: 66, width: 20, height: 4, type: 'path', fill: 'dirt' },
    { x: 160, y: 50, width: 6, height: 50, type: 'path', fill: 'dirt' },
    { x: 40, y: 30, width: 70, height: 4, type: 'path', fill: 'dirt' },
    { x: 180, y: 100, width: 6, height: 60, type: 'path', fill: 'dirt' },
    { x: 186, y: 28, width: 6, height: 12, type: 'path', fill: 'dirt' },
    { x: 96, y: 98, width: 24, height: 6, type: 'path', fill: 'stone' },
  ],
  portals: [
    { x: 120, y: 190, targetMap: 'forest', targetX: 150, targetY: 8 },
    { x: 120, y: 8, targetMap: 'village', targetX: 120, targetY: 150 },
    { x: 120, y: 28, targetMap: 'gilrhym', targetX: 150, targetY: 296 },
    { x: 100, y: 44, targetMap: 'shadow_castle', targetX: 100, targetY: 108 },
  ],
  chests: [
    { x: 170, y: 50, interactionId: 'shrine_chest' },
    { x: 110, y: 104, interactionId: 'mushroom_chest' },
    { x: 50, y: 136, interactionId: 'swamp_chest' },
    { x: 190, y: 90, interactionId: 'shadow_chest' },
    { x: 30, y: 30, interactionId: 'dark_hollow_chest' },
    { x: 210, y: 170, interactionId: 'cursed_chest' },
    { x: 165, y: 165, interactionId: 'treant_chest' },
    { x: 60, y: 65, interactionId: 'witch_chest' },
  ],
  interactables: [
    { x: 118, y: 38, type: 'bonfire', walkable: false, interactionId: 'bonfire_deep_woods_north' },
    { x: 52, y: 72, type: 'bonfire', walkable: false, interactionId: 'bonfire_deep_woods_west' },
    { x: 64, y: 66, type: 'sign', walkable: false, interactionId: 'witch_sign' },
    { x: 120, y: 30, type: 'sign', walkable: false, interactionId: 'temple_sign' },
    { x: 120, y: 175, type: 'sign', walkable: false, interactionId: 'deep_woods_sign' },
    { x: 100, y: 114, type: 'well', walkable: false, interactionId: 'ancient_fountain' },
    { x: 190, y: 95, type: 'campfire', walkable: false, interactionId: 'campfire' },
    { x: 115, y: 115, type: 'mushroom', walkable: true, interactionId: 'healing_mushroom' },
    { x: 205, y: 165, type: 'tombstone', walkable: false, interactionId: 'tombstone' },
    { x: 35, y: 25, type: 'campfire', walkable: false, interactionId: 'campfire' },
    { x: 55, y: 58, type: 'tempest_grass', walkable: true, interactionId: 'tempest_grass_pickup' },
    { x: 115, y: 108, type: 'tempest_grass', walkable: true, interactionId: 'tempest_grass_pickup' },
    { x: 185, y: 85, type: 'tempest_grass', walkable: true, interactionId: 'tempest_grass_pickup' },
    { x: 55, y: 135, type: 'tempest_grass', walkable: true, interactionId: 'tempest_grass_pickup' },
    { x: 165, y: 165, type: 'tempest_grass', walkable: true, interactionId: 'tempest_grass_pickup' },
    { x: 25, y: 165, type: 'tempest_grass', walkable: true, interactionId: 'tempest_grass_pickup' },
  ],
  props: [
    { x: 114, y: 178, type: 'lantern', walkable: false },
    { x: 126, y: 178, type: 'lantern', walkable: false },
    { x: 112, y: 177, type: 'dead_tree', walkable: false },
    { x: 128, y: 177, type: 'dead_tree', walkable: false },
    { x: 118, y: 166, type: 'bones_pile', walkable: true },
    { x: 122, y: 164, type: 'cage', walkable: false },
    { x: 162, y: 42, type: 'lantern', walkable: false },
    { x: 178, y: 42, type: 'lantern', walkable: false },
    { x: 168, y: 48, type: 'pot', walkable: true },
    { x: 172, y: 48, type: 'pot', walkable: true },
    { x: 175, y: 52, type: 'bones', walkable: true },
    { x: 164, y: 54, type: 'bones_pile', walkable: true },
    { x: 180, y: 54, type: 'chain', walkable: false },
    { x: 114, y: 24, type: 'pot', walkable: true },
    { x: 118, y: 26, type: 'pot', walkable: true },
    { x: 96, y: 92, type: 'altar', walkable: false },
    { x: 124, y: 92, type: 'altar', walkable: false },
    { x: 108, y: 84, type: 'chain', walkable: false },
    { x: 120, y: 84, type: 'chain', walkable: false },
    { x: 112, y: 96, type: 'lantern', walkable: false },
    { x: 92, y: 42, type: 'altar', walkable: false },
    { x: 108, y: 42, type: 'altar', walkable: false },
    { x: 98, y: 38, type: 'throne', walkable: false },
    { x: 102, y: 38, type: 'throne', walkable: false },
    { x: 94, y: 72, type: 'bloodstain', walkable: true },
    { x: 106, y: 72, type: 'bloodstain', walkable: true },
    { x: 100, y: 64, type: 'bloodstain', walkable: true },
    { x: 88, y: 52, type: 'bloodstain', walkable: true },
    { x: 112, y: 52, type: 'bloodstain', walkable: true },
    { x: 95, y: 48, type: 'bloodstain', walkable: true },
    { x: 105, y: 48, type: 'bloodstain', walkable: true },
    { x: 88, y: 86, type: 'bones_pile', walkable: true },
    { x: 112, y: 86, type: 'bones_pile', walkable: true },
    { x: 85, y: 45, type: 'bones_pile', walkable: true },
    { x: 115, y: 45, type: 'bones_pile', walkable: true },
    { x: 100, y: 56, type: 'bones_pile', walkable: true },
    { x: 96, y: 80, type: 'chain', walkable: false },
    { x: 104, y: 80, type: 'chain', walkable: false },
    { x: 90, y: 38, type: 'chain', walkable: false },
    { x: 110, y: 38, type: 'chain', walkable: false },
    { x: 92, y: 76, type: 'cage', walkable: false },
    { x: 108, y: 76, type: 'cage', walkable: false },
    { x: 86, y: 50, type: 'cage', walkable: false },
    { x: 114, y: 50, type: 'cage', walkable: false },
    { x: 48, y: 68, type: 'lantern', walkable: false },
    { x: 72, y: 68, type: 'lantern', walkable: false },
    { x: 52, y: 60, type: 'bones_pile', walkable: true },
    { x: 70, y: 58, type: 'stump', walkable: false },
    { x: 55, y: 58, type: 'cauldron', walkable: false },
    { x: 65, y: 62, type: 'cauldron', walkable: false },
    { x: 58, y: 66, type: 'altar', walkable: false },
  ],
  secretAreas: [
    { x: 15, y: 15, width: 8, height: 6, fill: 'stone' },
    { x: 210, y: 90, width: 8, height: 6, fill: 'grass' },
    { x: 225, y: 175, width: 6, height: 5, fill: 'stone' },
  ],
  elevationZones: [
    { x: 4, y: 2, width: 232, height: 54, elevation: 1 },
    { x: 84, y: 2, width: 120, height: 40, elevation: 2 },
    { x: 4, y: 58, width: 42, height: 52, elevation: 1 },
    { x: 172, y: 72, width: 64, height: 44, elevation: 1 },
    { x: 180, y: 78, width: 48, height: 28, elevation: 2 },
    { x: 150, y: 148, width: 82, height: 42, elevation: 1 },
  ],
  stairways: [
    { x: 116, y: 41, width: 8, height: 4, elevation: 2 },
    { x: 116, y: 55, width: 8, height: 4, elevation: 1 },
    { x: 180, y: 105, width: 6, height: 4, elevation: 2 },
    { x: 176, y: 115, width: 6, height: 4, elevation: 1 },
    { x: 38, y: 109, width: 6, height: 4, elevation: 1 },
    { x: 160, y: 189, width: 8, height: 4, elevation: 1 },
    { x: 210, y: 189, width: 6, height: 4, elevation: 1 },
  ],
  enemyZones: [
    { x: 50, y: 55, width: 20, height: 16, enemyType: 'shadow', count: 4 },
    { x: 30, y: 40, width: 24, height: 18, enemyType: 'shadow', count: 3 },
    { x: 155, y: 35, width: 22, height: 16, enemyType: 'shadow', count: 5 },
    { x: 168, y: 58, width: 16, height: 14, enemyType: 'shadow', count: 3 },
    { x: 145, y: 95, width: 20, height: 16, enemyType: 'skeleton', count: 8 },
    { x: 25, y: 160, width: 18, height: 14, enemyType: 'spider', count: 7 },
    { x: 20, y: 18, width: 28, height: 22, enemyType: 'spider', count: 6 },
    { x: 92, y: 58, width: 20, height: 18, enemyType: 'shadow', count: 4 },
    { x: 80, y: 20, width: 30, height: 24, enemyType: 'shadow', count: 6 },
    { x: 115, y: 10, width: 22, height: 18, enemyType: 'shadow', count: 5 },
    { x: 178, y: 82, width: 26, height: 22, enemyType: 'shadow', count: 8 },
    { x: 190, y: 150, width: 16, height: 14, enemyType: 'shadow', count: 6 },
    { x: 155, y: 155, width: 20, height: 16, enemyType: 'skeleton', count: 5 },
    { x: 20, y: 100, width: 18, height: 14, enemyType: 'spider', count: 6 },
    { x: 100, y: 102, width: 36, height: 24, enemyType: 'slime', count: 7 },
    { x: 38, y: 118, width: 20, height: 16, enemyType: 'slime', count: 5 },
    { x: 175, y: 138, width: 22, height: 16, enemyType: 'shadow', count: 5 },
    { x: 85, y: 35, width: 18, height: 14, enemyType: 'golem', count: 1 },
  ],
};
