import type { MapDefinition } from '@/data/mapGenerator';

export const ruinsDef: MapDefinition = {
  name: 'Ancient Ruins',
  subtitle: 'A civilization buried and forgotten',
  width: 200,
  height: 120,
  spawnPoint: { x: 100, y: 110 },
  seed: 512,
  baseTerrain: 'ruins',
  borderTile: 'stone',
  coastalSouthBorder: false,
  features: [
    { x: 80, y: 96, width: 40, height: 20, type: 'clearing', fill: 'stone' },
    { x: 15, y: 35, width: 40, height: 30, type: 'ruins' },
    { x: 20, y: 15, width: 28, height: 16, type: 'ruins' },
    { x: 140, y: 35, width: 40, height: 30, type: 'ruins' },
    { x: 146, y: 15, width: 28, height: 16, type: 'ruins' },
    { x: 70, y: 30, width: 60, height: 40, type: 'clearing', fill: 'stone' },
    { x: 80, y: 36, width: 40, height: 28, type: 'ruins' },
    { x: 86, y: 2, width: 28, height: 8, type: 'clearing', fill: 'ruins_floor' },
    { x: 84, y: 8, width: 32, height: 20, type: 'ruins' },
    { x: 165, y: 8, width: 20, height: 14, type: 'ruins' },
    { x: 5, y: 60, width: 20, height: 15, type: 'ruins' },
    { x: 96, y: 70, width: 8, height: 30, type: 'path', fill: 'stone' },
    { x: 40, y: 50, width: 50, height: 6, type: 'path', fill: 'stone' },
    { x: 110, y: 50, width: 40, height: 6, type: 'path', fill: 'stone' },
    { x: 30, y: 31, width: 6, height: 16, type: 'path', fill: 'stone' },
    { x: 160, y: 31, width: 6, height: 16, type: 'path', fill: 'stone' },
    { x: 96, y: 28, width: 8, height: 10, type: 'path', fill: 'stone' },
    { x: 130, y: 50, width: 8, height: 46, type: 'path', fill: 'stone' },
    { x: 60, y: 50, width: 8, height: 46, type: 'path', fill: 'stone' },
    { x: 130, y: 15, width: 35, height: 4, type: 'path', fill: 'stone' },
    { x: 15, y: 55, width: 6, height: 10, type: 'path', fill: 'stone' },
  ],
  portals: [
    { x: 100, y: 117, targetMap: 'deep_woods', targetX: 120, targetY: 30 },
    { x: 197, y: 110, targetMap: 'forest', targetX: 282, targetY: 22 },
  ],
  chests: [
    { x: 25, y: 45, interactionId: 'ruins_puzzle_chest' },
    { x: 160, y: 50, interactionId: 'ruins_combat_chest' },
    { x: 100, y: 14, interactionId: 'ancient_chest' },
    { x: 90, y: 44, interactionId: 'ruins_central_chest' },
    { x: 175, y: 14, interactionId: 'east_vault_chest' },
    { x: 12, y: 68, interactionId: 'library_chest' },
    { x: 150, y: 45, interactionId: 'ruins_arena_chest' },
    { x: 35, y: 22, interactionId: 'ruins_west_chest' },
  ],
  interactables: [
    { x: 100, y: 56, type: 'bonfire', walkable: false, interactionId: 'bonfire_ruins' },
    { x: 100, y: 50, type: 'well', walkable: false, interactionId: 'ancient_fountain' },
    { x: 35, y: 25, type: 'sign', walkable: false, interactionId: 'ancient_tablet' },
    { x: 160, y: 25, type: 'sign', walkable: false, interactionId: 'ancient_tablet_2' },
    { x: 100, y: 18, type: 'sign', walkable: false, interactionId: 'vault_inscription' },
    { x: 10, y: 65, type: 'sign', walkable: false, interactionId: 'library_tablet' },
    { x: 175, y: 12, type: 'campfire', walkable: false, interactionId: 'campfire' },
    { x: 88, y: 58, type: 'moonbloom', walkable: true, interactionId: 'moonbloom_pickup' },
    { x: 142, y: 62, type: 'moonbloom', walkable: true, interactionId: 'moonbloom_pickup' },
    { x: 48, y: 48, type: 'moonbloom', walkable: true, interactionId: 'moonbloom_pickup' },
  ],
  elevationZones: [
    { x: 14, y: 28, width: 48, height: 40, elevation: 1 },
    { x: 136, y: 28, width: 50, height: 40, elevation: 1 },
    { x: 66, y: 22, width: 68, height: 52, elevation: 1 },
    { x: 80, y: 6, width: 40, height: 28, elevation: 2 },
    { x: 158, y: 6, width: 30, height: 24, elevation: 2 },
    { x: 4, y: 56, width: 28, height: 22, elevation: 1 },
  ],
  stairways: [
    { x: 96, y: 32, width: 8, height: 4, elevation: 2 },
    { x: 96, y: 72, width: 8, height: 4, elevation: 1 },
    { x: 30, y: 66, width: 6, height: 4, elevation: 1 },
    { x: 158, y: 66, width: 6, height: 4, elevation: 1 },
    { x: 168, y: 28, width: 6, height: 4, elevation: 2 },
    { x: 12, y: 76, width: 6, height: 4, elevation: 1 },
  ],
  enemyZones: [
    { x: 140, y: 30, width: 44, height: 36, enemyType: 'shadow', count: 8 },
    { x: 70, y: 30, width: 60, height: 40, enemyType: 'shadow', count: 6 },
    { x: 84, y: 8, width: 32, height: 20, enemyType: 'shadow', count: 5 },
    { x: 15, y: 35, width: 40, height: 30, enemyType: 'skeleton', count: 4 },
    { x: 165, y: 8, width: 20, height: 14, enemyType: 'skeleton', count: 4 },
  ],
};
