import type { MapDefinition } from '@/data/mapGenerator';

export const shadowCastleDef: MapDefinition = {
  name: 'Shadow Castle',
  subtitle: 'Darkness made stone',
  width: 200,
  height: 120,
  spawnPoint: { x: 100, y: 108 },
  seed: 770,
  baseTerrain: 'ruins',
  borderTile: 'stone',
  coastalSouthBorder: false,
  features: [
    { x: 78, y: 96, width: 44, height: 20, type: 'clearing', fill: 'stone' },
    { x: 66, y: 88, width: 68, height: 20, type: 'clearing', fill: 'stone' },
    { x: 14, y: 68, width: 42, height: 32, type: 'ruins' },
    { x: 144, y: 68, width: 42, height: 32, type: 'ruins' },
    { x: 22, y: 30, width: 34, height: 28, type: 'ruins' },
    { x: 144, y: 30, width: 34, height: 28, type: 'ruins' },
    { x: 20, y: 82, width: 30, height: 12, type: 'clearing', fill: 'stone' },
    { x: 150, y: 82, width: 30, height: 12, type: 'clearing', fill: 'stone' },
    { x: 70, y: 46, width: 60, height: 44, type: 'clearing', fill: 'stone' },
    { x: 78, y: 52, width: 44, height: 32, type: 'ruins' },
    { x: 88, y: 44, width: 24, height: 18, type: 'clearing', fill: 'stone' },
    { x: 84, y: 6, width: 32, height: 30, type: 'clearing', fill: 'ruins_floor' },
    { x: 82, y: 10, width: 36, height: 24, type: 'boss_arena', interactionId: 'shadow_lord' },
    { x: 76, y: 0, width: 48, height: 12, type: 'clearing', fill: 'ruins_floor' },
    { x: 96, y: 34, width: 8, height: 64, type: 'path', fill: 'stone' },
    { x: 96, y: 96, width: 8, height: 20, type: 'path', fill: 'ruins_floor' },
    { x: 80, y: 92, width: 40, height: 6, type: 'path', fill: 'ruins_floor' },
    { x: 56, y: 72, width: 88, height: 6, type: 'path', fill: 'stone' },
    { x: 56, y: 42, width: 88, height: 6, type: 'path', fill: 'stone' },
    { x: 48, y: 42, width: 8, height: 36, type: 'path', fill: 'stone' },
    { x: 144, y: 42, width: 8, height: 36, type: 'path', fill: 'stone' },
    { x: 36, y: 82, width: 20, height: 4, type: 'path', fill: 'stone' },
    { x: 144, y: 82, width: 20, height: 4, type: 'path', fill: 'stone' },
  ],
  portals: [
    { x: 100, y: 117, targetMap: 'deep_woods', targetX: 100, targetY: 44 },
    { x: 100, y: 4, targetMap: 'village', targetX: 120, targetY: 70 },
  ],
  chests: [
    { x: 38, y: 84, interactionId: 'shadow_castle_west_chest' },
    { x: 162, y: 84, interactionId: 'shadow_castle_east_chest' },
    { x: 100, y: 58, interactionId: 'shadow_castle_hall_chest' },
    { x: 100, y: 12, interactionId: 'boss_arena_chest' },
  ],
  interactables: [
    { x: 100, y: 101, type: 'bonfire', walkable: false, interactionId: 'bonfire_shadow_castle' },
    { x: 100, y: 40, type: 'sign', walkable: false, interactionId: 'temple_sign' },
    { x: 100, y: 52, type: 'sign', walkable: false, interactionId: 'shadow_castle_gate_switch' },
    { x: 84, y: 88, type: 'campfire', walkable: false, interactionId: 'campfire' },
    { x: 116, y: 88, type: 'campfire', walkable: false, interactionId: 'campfire' },
  ],
  props: [
    { x: 84, y: 102, type: 'campfire', walkable: false },
    { x: 116, y: 102, type: 'campfire', walkable: false },
    { x: 78, y: 96, type: 'lantern', walkable: false },
    { x: 122, y: 96, type: 'lantern', walkable: false },
    { x: 88, y: 98, type: 'bones_pile', walkable: true },
    { x: 112, y: 98, type: 'bones_pile', walkable: true },
    { x: 92, y: 94, type: 'chain', walkable: false },
    { x: 108, y: 94, type: 'chain', walkable: false },
    { x: 90, y: 92, type: 'chain', walkable: false },
    { x: 110, y: 92, type: 'chain', walkable: false },
    { x: 88, y: 84, type: 'bones_pile', walkable: true },
    { x: 112, y: 84, type: 'bones_pile', walkable: true },
    { x: 30, y: 86, type: 'altar', walkable: false },
    { x: 42, y: 86, type: 'cage', walkable: false },
    { x: 38, y: 92, type: 'bones_pile', walkable: true },
    { x: 28, y: 78, type: 'lantern', walkable: false },
    { x: 158, y: 86, type: 'altar', walkable: false },
    { x: 170, y: 86, type: 'cage', walkable: false },
    { x: 162, y: 92, type: 'bones_pile', walkable: true },
    { x: 172, y: 78, type: 'lantern', walkable: false },
    { x: 96, y: 70, type: 'altar', walkable: false },
    { x: 104, y: 70, type: 'altar', walkable: false },
    { x: 92, y: 60, type: 'lantern', walkable: false },
    { x: 108, y: 60, type: 'lantern', walkable: false },
    { x: 90, y: 54, type: 'bones_pile', walkable: true },
    { x: 110, y: 54, type: 'bones_pile', walkable: true },
    { x: 84, y: 50, type: 'chain', walkable: false },
    { x: 116, y: 50, type: 'chain', walkable: false },
    { x: 95, y: 28, type: 'throne', walkable: false },
    { x: 105, y: 28, type: 'throne', walkable: false },
    { x: 88, y: 24, type: 'altar', walkable: false },
    { x: 112, y: 24, type: 'altar', walkable: false },
    { x: 92, y: 16, type: 'cage', walkable: false },
    { x: 108, y: 16, type: 'cage', walkable: false },
    { x: 96, y: 12, type: 'lantern', walkable: false },
    { x: 104, y: 12, type: 'lantern', walkable: false },
  ],
  elevationZones: [
    { x: 6, y: 22, width: 188, height: 74, elevation: 1 },
    { x: 74, y: 2, width: 52, height: 42, elevation: 2 },
    { x: 16, y: 26, width: 44, height: 36, elevation: 1 },
    { x: 140, y: 26, width: 44, height: 36, elevation: 1 },
  ],
  stairways: [
    { x: 96, y: 44, width: 8, height: 4, elevation: 2 },
    { x: 96, y: 96, width: 8, height: 4, elevation: 1 },
    { x: 52, y: 62, width: 6, height: 4, elevation: 1 },
    { x: 144, y: 62, width: 6, height: 4, elevation: 1 },
  ],
  enemyZones: [
    { x: 78, y: 88, width: 44, height: 20, enemyType: 'shadow', count: 6 },
    { x: 24, y: 76, width: 24, height: 18, enemyType: 'skeleton', count: 4 },
    { x: 152, y: 76, width: 24, height: 18, enemyType: 'skeleton', count: 4 },
    { x: 84, y: 54, width: 32, height: 22, enemyType: 'shadow', count: 7 },
    { x: 84, y: 10, width: 30, height: 22, enemyType: 'golem', count: 1 },
  ],
};
